insert into user(email, name, created_date, modified_date) values ('user1111@test.com', 'user1111', sysdate, sysdate)
insert into user(email, name, created_date, modified_date) values ('user2222@test.com', 'user2222', sysdate, sysdate)
insert into user(email, name, created_date, modified_date) values ('user3333@test.com', 'user3333', sysdate, sysdate)
insert into user(email, name, created_date, modified_date) values ('user4444@test.com', 'user4444', sysdate, sysdate)
insert into user(email, name, created_date, modified_date) values ('user5555@test.com', 'user5555', sysdate, sysdate)